import React from 'react'

export default function IrregularVerbs() {
  return (
    <div>
      <h2>Irregular Verbs</h2>
      <table className='ui very compact celled blue unstackable table'>
        <thead>
          <tr>
            <th>V1</th>
            <th>V2</th>
            <th>V3</th>
            <th>V4</th>
          </tr>
        </thead>
        <tbody>
          <tr><td>beat</td><td>beat</td><td>beaten</td><td>beating</td></tr>
          <tr><td>become</td><td>became</td><td>become</td><td>becoming</td></tr>
          <tr><td>begin</td><td>began</td><td>begun</td><td>begining</td></tr>
          <tr><td>bend</td><td>bent</td><td>bent</td><td>bending</td></tr>
          <tr><td>bet</td><td>bet</td><td>bet</td><td>betting</td></tr>
          <tr><td>bid</td><td>bid</td><td>bid</td><td>biding</td></tr>
          <tr><td>bite</td><td>bit</td><td>bitten</td><td>biting</td></tr>
          <tr><td>blow</td><td>blew</td><td>blown</td><td>blowing</td></tr>
          <tr><td>break</td><td>broke</td><td>broken</td><td>breaking</td></tr>
          <tr><td>bring</td><td>brought</td><td>brought</td><td>bringing</td></tr>
          <tr><td>build</td><td>built</td><td>built</td><td>building</td></tr>
          <tr><td>burn</td><td>burned</td><td>burnt</td><td>burning</td></tr>
          <tr><td>buy</td><td>bought</td><td>bought</td><td>buying</td></tr>
          <tr><td>catch</td><td>caught</td><td>caught</td><td>catching</td></tr>
          <tr><td>choose</td><td>chose</td><td>chosen</td><td>choosing</td></tr>
          <tr><td>come</td><td>came</td><td>come</td><td>coming</td></tr>
          <tr><td>cost</td><td>cost</td><td>cost</td><td>costing</td></tr>
          <tr><td>cut</td><td>cut</td><td>cut</td><td>cutting</td></tr>
          <tr><td>dig</td><td>dug</td><td>dug</td><td>diging</td></tr>
          <tr><td>dive</td><td>dove</td><td>dived</td><td>diving</td></tr>
          <tr><td>do</td><td>did</td><td>done</td><td>doing</td></tr>
          <tr><td>draw</td><td>drew</td><td>drawn</td><td>drawing</td></tr>
          <tr><td>dream</td><td>dreamed</td><td>dreamed</td><td>dreaming</td></tr>
          <tr><td>drive</td><td>drove</td><td>driven</td><td>driving</td></tr>
          <tr><td>drink</td><td>drank</td><td>drunk</td><td>drinking</td></tr>
          <tr><td>eat</td><td>ate</td><td>eaten</td><td>eating</td></tr>
          <tr><td>fall</td><td>fell</td><td>fallen</td><td>falling</td></tr>
          <tr><td>feel</td><td>felt</td><td>felt</td><td>feeling</td></tr>
          <tr><td>fight</td><td>fought</td><td>fought</td><td>fighting</td></tr>
          <tr><td>find</td><td>found</td><td>found</td><td>finding</td></tr>
          <tr><td>fly</td><td>flew</td><td>flown</td><td>flying</td></tr>
          <tr><td>forget</td><td>forgot</td><td>forgotten</td><td>forgetting</td></tr>
          <tr><td>forgive</td><td>forgave</td><td>forgiven</td><td>forgiving</td></tr>
          <tr><td>freeze</td><td>froze</td><td>frozen</td><td>freezing</td></tr>
          <tr><td>get</td><td>got</td><td>gotten</td><td>getting</td></tr>
          <tr><td>give</td><td>gave</td><td>given</td><td>giving</td></tr>
          <tr><td>go</td><td>went</td><td>gone</td><td>going</td></tr>
          <tr><td>grow</td><td>grew</td><td>grown</td><td>growing</td></tr>
          <tr><td>hang</td><td>hung</td><td>hung</td><td>hanging</td></tr>
          <tr><td>have</td><td>had</td><td>had</td><td>having</td></tr>
          <tr><td>hear</td><td>heard</td><td>heard</td><td>hearing</td></tr>
          <tr><td>hide</td><td>hid</td><td>hidden</td><td>hiding</td></tr>
          <tr><td>hit</td><td>hit</td><td>hit</td><td>hitting</td></tr>
          <tr><td>hold</td><td>held</td><td>held</td><td>holding</td></tr>
          <tr><td>hurt</td><td>hurt</td><td>hurt</td><td>hurtting</td></tr>
          <tr><td>keep</td><td>kept</td><td>kept</td><td>keeping</td></tr>
          <tr><td>know</td><td>knew</td><td>known</td><td>knowing</td></tr>
          <tr><td>lay</td><td>laid</td><td>laid</td><td>laying</td></tr>
          <tr><td>lead</td><td>led</td><td>led</td><td>leading</td></tr>
          <tr><td>leave</td><td>left</td><td>left</td><td>leaving</td></tr>
          <tr><td>lend</td><td>lent</td><td>lent</td><td>lending</td></tr>
          <tr><td>let</td><td>let</td><td>let</td><td>letting</td></tr>
          <tr><td>lie</td><td>lay</td><td>lain</td><td>lying</td></tr>
          <tr><td>lose</td><td>lost</td><td>lost</td><td>losing</td></tr>
          <tr><td>make</td><td>made</td><td>made</td><td>making</td></tr>
          <tr><td>mean</td><td>meant</td><td>meant</td><td>meaning</td></tr>
          <tr><td>meet</td><td>met</td><td>met</td><td>meeting</td></tr>
          <tr><td>pay</td><td>paid</td><td>paid</td><td>paying</td></tr>
          <tr><td>put</td><td>put</td><td>put</td><td>puting</td></tr>
          <tr><td>read</td><td>read</td><td>read</td><td>reading</td></tr>
          <tr><td>ride</td><td>rode</td><td>ridden</td><td>riding</td></tr>
          <tr><td>ring</td><td>rang</td><td>rung</td><td>ringing</td></tr>
          <tr><td>rise</td><td>rose</td><td>risen</td><td>rising</td></tr>
          <tr><td>run</td><td>ran</td><td>run</td><td>runing</td></tr>
          <tr><td>say</td><td>said</td><td>said</td><td>saying</td></tr>
          <tr><td>see</td><td>saw</td><td>seen</td><td>seeing</td></tr>
          <tr><td>sell</td><td>sold</td><td>sold</td><td>selling</td></tr>
          <tr><td>send</td><td>sent</td><td>sent</td><td>sending</td></tr>
          <tr><td>show</td><td>showed</td><td>shown</td><td>showing</td></tr>
          <tr><td>shut</td><td>shut</td><td>shut</td><td>shuting</td></tr>
          <tr><td>sing</td><td>sang</td><td>sung</td><td>singing</td></tr>
          <tr><td>sit</td><td>sat</td><td>sat</td><td>siting</td></tr>
          <tr><td>sleep</td><td>slept</td><td>slept</td><td>sleeping</td></tr>
          <tr><td>speak</td><td>spoke</td><td>spoken</td><td>speaking</td></tr>
          <tr><td>spend</td><td>spent</td><td>spent</td><td>spending</td></tr>
          <tr><td>stand</td><td>stood</td><td>stood</td><td>standing</td></tr>
          <tr><td>swim</td><td>swam</td><td>swum</td><td>swiming</td></tr>
          <tr><td>take</td><td>took</td><td>taken</td><td>taking</td></tr>
          <tr><td>teach</td><td>taught</td><td>taught</td><td>teaching</td></tr>
          <tr><td>tear</td><td>tore</td><td>torn</td><td>tearing</td></tr>
          <tr><td>tell</td><td>told</td><td>told</td><td>telling</td></tr>
          <tr><td>think</td><td>thought</td><td>thought</td><td>thinking</td></tr>
          <tr><td>throw</td><td>threw</td><td>thrown</td><td>throwing</td></tr>
          <tr><td>wake</td><td>woke</td><td>woken</td><td>waking</td></tr>
          <tr><td>wear</td><td>wore</td><td>worn</td><td>wearing</td></tr>
          <tr><td>win</td><td>won</td><td>won</td><td>wining</td></tr>
          <tr><td>write</td><td>wrote</td><td>written</td><td>writing</td></tr>
        </tbody>
      </table>
    </div>
  )
}
