import React from 'react'

export default function Opposites() {
  return (
    <>
      <table id='opp-table' className='ui blue unstackable table'>
        <tr>
          <td>Antonym</td>
          <td>Synonym</td>
        </tr>
        <tr>
          <td>
            Approximately
            <div></div>
            تقریبن
          </td>
          <td>Exactly
            <div></div>
            بالکل</td>
        </tr>
        <tr>
          <td>Ask
            <div></div>
            پوچھو
          </td>
          <td>Reply
            <div></div>
            جواب دو
          </td>
        </tr>
        <tr>
          <td>Authentic
            <div></div>
            صحیح
          </td>
          <td>Fake
            <div></div>
            جالی / نقلی / جھوٹا
          </td>
        </tr>
        <tr>
          <td>Awake
            <div>جگنا</div>
          </td>
          <td>Asleep
            <div>سونا</div>
          </td>
        </tr>
        <tr>
          <td>Bad
            <div>خراب</div>
          </td>
          <td>Good
            <div></div>
            اچھا
          </td>
        </tr>
        <tr>
          <td>Beautiful</td>
          <td>Ugly</td>
        </tr>
        <tr>
          <td>Before</td>
          <td>After</td>
        </tr>
        <tr>
          <td>Boy</td>
          <td>Girl</td>
        </tr>
        <tr>
          <td>Bold</td>
          <td>Timid</td>
        </tr>
        <tr>
          <td>Bright</td>
          <td>Dim</td>
        </tr>
        <tr>
          <td>Broad</td>
          <td>Narrow</td>
        </tr>
        <tr>
          <td>Best</td>
          <td>Worst</td>
        </tr>
        <tr>
          <td>Child</td>
          <td>Adult</td>
        </tr>
        <tr>
          <td>Changeable</td>
          <td>Constant</td>
        </tr>
        <tr>
          <td>Clemency</td>
          <td>Ruthlessness</td>
        </tr>
        <tr>
          <td>Concise</td>
          <td>Lengthy</td>
        </tr>
        <tr>
          <td>Construction</td>
          <td>Destruction</td>
        </tr>
        <tr>
          <td>Delicious</td>
          <td>Awful</td>
        </tr>
        <tr>
          <td>Descent</td>
          <td>Ascent</td>
        </tr>
        <tr>
          <td>Dictatorship</td>
          <td>Republic</td>
        </tr>
        <tr>
          <td>Domestic</td>
          <td>Foreign</td>
        </tr>
        <tr>
          <td>Dwindle</td>
          <td>Flourish</td>
        </tr>
        <tr>
          <td>Early</td>
          <td>Late</td>
        </tr>
        <tr>
          <td>Entrance</td>
          <td>Exit</td>
        </tr>
        <tr>
          <td>Even</td>
          <td>Odd</td>
        </tr>
        <tr>
          <td>Eccentric</td>
          <td>Ordinary</td>
        </tr>
        <tr>
          <td>Far</td>
          <td>Near</td>
        </tr>
        <tr>
          <td>Friend</td>
          <td>Enemy</td>
        </tr>
        <tr>
          <td>Full</td>
          <td>Empty</td>
        </tr>
        <tr>
          <td>Funny</td>
          <td>Serious</td>
        </tr>
        <tr>
          <td>Frequently</td>
          <td>Occasionally</td>
        </tr>
        <tr>
          <td>General</td>
          <td>Particular</td>
        </tr>
        <tr>
          <td>Generous</td>
          <td>Mean</td>
        </tr>
        <tr>
          <td>Gentle</td>
          <td>Violent</td>
        </tr>
        <tr>
          <td>Give</td>
          <td>Take</td>
        </tr>
        <tr>
          <td>Happy</td>
          <td>Sad</td>
        </tr>
        <tr>
          <td>Hard</td>
          <td>Easy</td>
        </tr>
        <tr>
          <td>Heavy</td>
          <td>Light</td>
        </tr>
        <tr>
          <td>Honest</td>
          <td>Dishonest</td>
        </tr>
        <tr>
          <td>Hot</td>
          <td>Cold</td>
        </tr>
        <tr>
          <td>Hopeful</td>
          <td>Desperate</td>
        </tr>
        <tr>
          <td>Horizontal</td>
          <td>Vertical</td>
        </tr>
        <tr>
          <td>Humid</td>
          <td>Dry</td>
        </tr>
        <tr>
          <td>Import</td>
          <td>Export</td>
        </tr>
        <tr>
          <td>Inside</td>
          <td>Outside</td>
        </tr>
        <tr>
          <td>In</td>
          <td>Out</td>
        </tr>
        <tr>
          <td>Interesting</td>
          <td>Boring</td>
        </tr>
        <tr>
          <td>Junior</td>
          <td>Senior</td>
        </tr>
        <tr>
          <td>Kind</td>
          <td>Cruel</td>
        </tr>
        <tr>
          <td>Large</td>
          <td>Small</td>
        </tr>
        <tr>
          <td>Lead</td>
          <td>Follow</td>
        </tr>
        <tr>
          <td>Lend</td>
          <td>Borrow</td>
        </tr>
        <tr>
          <td>Light</td>
          <td>Dark</td>
        </tr>
        <tr>
          <td>Love</td>
          <td>Hate</td>
        </tr>
        <tr>
          <td>Little</td>
          <td>Big</td>
        </tr>
        <tr>
          <td>Laugh</td>
          <td>Cry</td>
        </tr>
        <tr>
          <td>Left</td>
          <td>Right</td>
        </tr>
        <tr>
          <td>Liquid</td>
          <td>Solid</td>
        </tr>
        <tr>
          <td>Mend</td>
          <td>Break</td>
        </tr>
        <tr>
          <td>Mess</td>
          <td>Order</td>
        </tr>
        <tr>
          <td>Moderate</td>
          <td>Extreme</td>
        </tr>
        <tr>
          <td>More</td>
          <td>Less</td>
        </tr>
        <tr>
          <td>Man</td>
          <td>Woman</td>
        </tr>
        <tr>
          <td>Messy</td>
          <td>Neat</td>
        </tr>
        <tr>
          <td>Modern</td>
          <td>Ancient</td>
        </tr>
        <tr>
          <td>Normal</td>
          <td>Strange</td>
        </tr>
        <tr>
          <td>Opposite</td>
          <td>Same</td>
        </tr>
        <tr>
          <td>Opponent</td>
          <td>Supporter</td>
        </tr>
        <tr>
          <td>Praise</td>
          <td>Castigate</td>
        </tr>
        <tr>
          <td>Refuse</td>
          <td>Agree</td>
        </tr>
        <tr>
          <td>Regret</td>
          <td>Satisfaction</td>
        </tr>
        <tr>
          <td>Rich</td>
          <td>Poor</td>
        </tr>
        <tr>
          <td>Rude</td>
          <td>Polite</td>
        </tr>
        <tr>
          <td>Start</td>
          <td>End</td>
        </tr>
        <tr>
          <td>Sunny</td>
          <td>Cloudy</td>
        </tr>
        <tr>
          <td>Sweet</td>
          <td>Sour</td>
        </tr>
        <tr>
          <td>Strengthen</td>
          <td>Debilitate</td>
        </tr>
        <tr>
          <td>Tight</td>
          <td>Loose</td>
        </tr>
        <tr>
          <td>Top</td>
          <td>Bottom</td>
        </tr>
        <tr>
          <td>Thick</td>
          <td>Thin</td>
        </tr>
        <tr>
          <td>Tiny</td>
          <td>Huge</td>
        </tr>
        <tr>
          <td>Truth</td>
          <td>Lie</td>
        </tr>
        <tr>
          <td>Unity</td>
          <td>Division</td>
        </tr>
        <tr>
          <td>Useful</td>
          <td>Useless</td>
        </tr>
        <tr>
          <td>Victory</td>
          <td>Defeat</td>
        </tr>
        <tr>
          <td>Victory</td>
          <td>Defeat</td>
        </tr>
        <tr>
          <td>Visible</td>
          <td>Invisible</td>
        </tr>
        <tr>
          <td>Visitor</td>
          <td>Host</td>
        </tr>
        <tr>
          <td>Wide</td>
          <td>Narrow</td>
        </tr>
        <tr>
          <td>Wise</td>
          <td>Foolish</td>
        </tr>
        <tr>
          <td>Whisper</td>
          <td>Scream</td>
        </tr>
        <tr>
          <td>Adorable</td>
          <td>Hateful</td>
        </tr>
        <tr>
          <td>Adequate</td>
          <td>Insufficient</td>
        </tr>
        <tr>
          <td>Affordable</td>
          <td>Costly</td>
        </tr>
        <tr>
          <td>Attractive</td>
          <td>Boring</td>
        </tr>
        <tr>
          <td>Awesome</td>
          <td>Bad</td>
        </tr>
        <tr>
          <td>Abundance</td>
          <td>Lack</td>
        </tr>
        <tr>
          <td>Accidental</td>
          <td>Intentional</td>
        </tr>
        <tr>
          <td>Advanced</td>
          <td>Elementary</td>
        </tr>
        <tr>
          <td>Affable</td>
          <td>Unfriendly</td>
        </tr>
        <tr>
          <td>Amateur</td>
          <td>Professional</td>
        </tr>
        <tr>
          <td>Amiable</td>
          <td>Grumpy</td>
        </tr>
        <tr>
          <td>Ancestor</td>
          <td>Descendant</td>
        </tr>
        <tr>
          <td>Beauty</td>
          <td>Grotesqueness</td>
        </tr>
        <tr>
          <td>Believe</td>
          <td>Disbelieve</td>
        </tr>
        <tr>
          <td>Beloved</td>
          <td>Unbeloved</td>
        </tr>
        <tr>
          <td>Benefit</td>
          <td>Drawback</td>
        </tr>
        <tr>
          <td>Balk</td>
          <td>Impetus</td>
        </tr>
        <tr>
          <td>Beneficial</td>
          <td>Detrimental</td>
        </tr>
        <tr>
          <td>Care</td>
          <td>Carelessness</td>
        </tr>
        <tr>
          <td>Carry</td>
          <td>Exclude</td>
        </tr>
        <tr>
          <td>Cavalier</td>
          <td>Humble</td>
        </tr>
        <tr>
          <td>Clumsy</td>
          <td>Adroit</td>
        </tr>
        <tr>
          <td>Creative</td>
          <td>Uninventive</td>
        </tr>
        <tr>
          <td>Cut</td>
          <td>Restore</td>
        </tr>
        <tr>
          <td>Close</td>
          <td>Far</td>
        </tr>
        <tr>
          <td>Darling</td>
          <td>Unbeloved</td>
        </tr>
        <tr>
          <td>Dear</td>
          <td>Unbeloved</td>
        </tr>
        <tr>
          <td>Deep</td>
          <td>Shallow</td>
        </tr>
        <tr>
          <td>Demand</td>
          <td>Disclaim</td>
        </tr>
        <tr>
          <td>Destroy</td>
          <td>Raise</td>
        </tr>
        <tr>
          <td>Effective</td>
          <td>Ineffective</td>
        </tr>
        <tr>
          <td>Efficient</td>
          <td>Inefficient</td>
        </tr>
        <tr>
          <td>Effort</td>
          <td>Ease</td>
        </tr>
        <tr>
          <td>Enjoy</td>
          <td>Abhor</td>
        </tr>
        <tr>
          <td>Enough</td>
          <td>Inadequate</td>
        </tr>
        <tr>
          <td>Emigrate</td>
          <td>Immigrate</td>
        </tr>
        <tr>
          <td>Enslave</td>
          <td>Emancipate</td>
        </tr>
        <tr>
          <td>Ephemeral</td>
          <td>Long-lived</td>
        </tr>
        <tr>
          <td>Excitable</td>
          <td>Tranquil</td>
        </tr>
        <tr>
          <td>Fabulous</td>
          <td>Ordinary</td>
        </tr>
        <tr>
          <td>Fair</td>
          <td>Foul</td>
        </tr>
        <tr>
          <td>Fast</td>
          <td>Slow</td>
        </tr>
        <tr>
          <td>Few</td>
          <td>Many</td>
        </tr>
        <tr>
          <td>Flaccid</td>
          <td>Taut</td>
        </tr>
        <tr>
          <td>Forgive</td>
          <td>Resent</td>
        </tr>
        <tr>
          <td>Gentle</td>
          <td>Abrasive</td>
        </tr>
        <tr>
          <td>Great</td>
          <td>Little</td>
        </tr>
        <tr>
          <td>Genius</td>
          <td>Stupidity</td>
        </tr>
        <tr>
          <td>Glad</td>
          <td>Dismayed</td>
        </tr>
        <tr>
          <td>Gorgeous</td>
          <td>Uninteresting</td>
        </tr>
        <tr>
          <td>Habit</td>
          <td>Disinclination</td>
        </tr>
        <tr>
          <td>Happy</td>
          <td>Sad</td>
        </tr>
        <tr>
          <td>Help</td>
          <td>Hinder</td>
        </tr>
        <tr>
          <td>Humanity</td>
          <td>Inhumanity</td>
        </tr>
        <tr>
          <td>Hurt</td>
          <td>Heal</td>
        </tr>
        <tr>
          <td>Illegal</td>
          <td>Legal</td>
        </tr>
        <tr>
          <td>Ignominy</td>
          <td>Glory</td>
        </tr>
        <tr>
          <td>Impress</td>
          <td>Disappoint</td>
        </tr>
        <tr>
          <td>Intrepid</td>
          <td>Cowardly</td>
        </tr>
        <tr>
          <td>Independent</td>
          <td>Dependent</td>
        </tr>
        <tr>
          <td>Inception</td>
          <td>Conclusion</td>
        </tr>
        <tr>
          <td>Innocent</td>
          <td>Guilty</td>
        </tr>
        <tr>
          <td>Inspire</td>
          <td>Depress</td>
        </tr>
        <tr>
          <td>Install</td>
          <td>Remove</td>
        </tr>
        <tr>
          <td>Joke</td>
          <td>Humourless</td>
        </tr>
        <tr>
          <td>Jolly</td>
          <td>Miserable</td>
        </tr>
        <tr>
          <td>Joy</td>
          <td>Misery</td>
        </tr>
        <tr>
          <td>Justice</td>
          <td>Injustice</td>
        </tr>
        <tr>
          <td>Justify</td>
          <td>Disprove</td>
        </tr>
        <tr>
          <td>Keen</td>
          <td>Reluctant</td>
        </tr>
        <tr>
          <td>Keep</td>
          <td>Spend</td>
        </tr>
        <tr>
          <td>Kickoff</td>
          <td>End</td>
        </tr>
        <tr>
          <td>Kind</td>
          <td>Unkind</td>
        </tr>
        <tr>
          <td>Knowledge</td>
          <td>Ignorance</td>
        </tr>
        <tr>
          <td>Little</td>
          <td>Plenty</td>
        </tr>
        <tr>
          <td>Lively</td>
          <td>Listless</td>
        </tr>
        <tr>
          <td>Lost</td>
          <td>Regain</td>
        </tr>
        <tr>
          <td>Love</td>
          <td>Hatred</td>
        </tr>
        <tr>
          <td>Luck</td>
          <td>Misfortune</td>
        </tr>
        <tr>
          <td>Magic</td>
          <td>Awful</td>
        </tr>
        <tr>
          <td>Make</td>
          <td>Destroy</td>
        </tr>
        <tr>
          <td>Master</td>
          <td>Servant</td>
        </tr>
        <tr>
          <td>Mature</td>
          <td>Immature</td>
        </tr>
        <tr>
          <td>Morality</td>
          <td>Immorality</td>
        </tr>
        <tr>
          <td>Neat</td>
          <td>Disorderly</td>
        </tr>
        <tr>
          <td>Need</td>
          <td>Optional</td>
        </tr>
        <tr>
          <td>Next</td>
          <td>Previous</td>
        </tr>
        <tr>
          <td>Nice</td>
          <td>Unpleasant</td>
        </tr>
        <tr>
          <td>Normal</td>
          <td>Abnormal</td>
        </tr>
        <tr>
          <td>Objective</td>
          <td>Biassed</td>
        </tr>
        <tr>
          <td>Odium</td>
          <td>Affection</td>
        </tr>
        <tr>
          <td>Offer</td>
          <td>Withdraw</td>
        </tr>
        <tr>
          <td>Omnipotent</td>
          <td>Impotent</td>
        </tr>
        <tr>
          <td>Optimistic</td>
          <td>Pessimistic</td>
        </tr>
        <tr>
          <td>Outstanding</td>
          <td>Mediocre</td>
        </tr>
        <tr>
          <td>Pause</td>
          <td>Continue</td>
        </tr>
        <tr>
          <td>Peace</td>
          <td>Noise</td>
        </tr>
        <tr>
          <td>Potential</td>
          <td>Impotence</td>
        </tr>
        <tr>
          <td>Power</td>
          <td>Inability</td>
        </tr>
        <tr>
          <td>Pretty</td>
          <td>Plain</td>
        </tr>
        <tr>
          <td>Qualify</td>
          <td>Disqualify</td>
        </tr>
        <tr>
          <td>Quality</td>
          <td>Inadequacy</td>
        </tr>
        <tr>
          <td>Quick</td>
          <td>Slow</td>
        </tr>
        <tr>
          <td>Quiet</td>
          <td>Loud</td>
        </tr>
        <tr>
          <td>Quit</td>
          <td>Stay</td>
        </tr>
        <tr>
          <td>Real</td>
          <td>Unreal</td>
        </tr>
        <tr>
          <td>Recall</td>
          <td>Forget</td>
        </tr>
        <tr>
          <td>Relax</td>
          <td>Tense</td>
        </tr>
        <tr>
          <td>Report</td>
          <td>Silence</td>
        </tr>
        <tr>
          <td>Rough</td>
          <td>Gentle</td>
        </tr>
        <tr>
          <td>Simple</td>
          <td>Difficult</td>
        </tr>
        <tr>
          <td>Sincere</td>
          <td>Perfunctory</td>
        </tr>
        <tr>
          <td>Small</td>
          <td>Big</td>
        </tr>
        <tr>
          <td>Soft</td>
          <td>Hard</td>
        </tr>
        <tr>
          <td>Sure</td>
          <td>Unsure</td>
        </tr>
        <tr>
          <td>Talent</td>
          <td>Inability</td>
        </tr>
        <tr>
          <td>Talkative</td>
          <td>Taciturn</td>
        </tr>
        <tr>
          <td>Target</td>
          <td>Deselect</td>
        </tr>
        <tr>
          <td>Task</td>
          <td>Inactivity</td>
        </tr>
        <tr>
          <td>Tenderhearted</td>
          <td>Fiendish</td>
        </tr>
        <tr>
          <td>Triumph</td>
          <td>Defeat</td>
        </tr>
        <tr>
          <td>Unique</td>
          <td>Common</td>
        </tr>
        <tr>
          <td>Upturn</td>
          <td>Slump</td>
        </tr>
        <tr>
          <td>Unite</td>
          <td>Divide</td>
        </tr>
        <tr>
          <td>Unlimited</td>
          <td>Finite</td>
        </tr>
        <tr>
          <td>Uplift</td>
          <td>Lower</td>
        </tr>
        <tr>
          <td>Useful</td>
          <td>Useless</td>
        </tr>
        <tr>
          <td>Valid</td>
          <td>Invalid</td>
        </tr>
        <tr>
          <td>Valuable</td>
          <td>Worthless</td>
        </tr>
        <tr>
          <td>Variety</td>
          <td>Uniformity</td>
        </tr>
        <tr>
          <td>Vast</td>
          <td>Tiny</td>
        </tr>
        <tr>
          <td>Victory</td>
          <td>Defeat</td>
        </tr>
        <tr>
          <td>Warning</td>
          <td>Neglect</td>
        </tr>
        <tr>
          <td>Wealth</td>
          <td>Poverty</td>
        </tr>
        <tr>
          <td>Winner</td>
          <td>Loser</td>
        </tr>
        <tr>
          <td>Wise</td>
          <td>Stupid</td>
        </tr>
        <tr>
          <td>Worthy</td>
          <td>Unimportant</td>
        </tr>
        <tr>
          <td>Xenial</td>
          <td>Inhospitable</td>
        </tr>
        <tr>
          <td>Xenophobic</td>
          <td>Impartial</td>
        </tr>
        <tr>
          <td>Xeroxes</td>
          <td>Original</td>
        </tr>
        <tr>
          <td>Young</td>
          <td>Old</td>
        </tr>
        <tr>
          <td>Yield</td>
          <td>Resist</td>
        </tr>
        <tr>
          <td>Yearning</td>
          <td>Disinclination</td>
        </tr>
        <tr>
          <td>Youthful</td>
          <td>Old</td>
        </tr>
        <tr>
          <td>Yummy</td>
          <td>Unappetizing</td>
        </tr>
        <tr>
          <td>Zappy</td>
          <td>Melancholy</td>
        </tr>
        <tr>
          <td>Zany</td>
          <td>Sane</td>
        </tr>
        <tr>
          <td>Zeal</td>
          <td>Apathy</td>
        </tr>
        <tr>
          <td>Zenith</td>
          <td>Nadir</td>
        </tr>
        <tr>
          <td>Zen</td>
          <td>Disturbed</td>
        </tr>
        <tr>
          <td>Zingy</td>
          <td>Sullen</td>
        </tr>
      </table>
    </>
  )
}
